=== hskally20/atividades-pos-2024/xml/prato.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:p="http://prato.org"
        targetNamespace="http://prato.org"
        elementFormDefault="qualified">

    <element name="prato">
        <complexType>
            <sequence>
                <element name="nome">
                    <simpleType>
                        <restriction base="string">
                            <maxLength value="100"/>
                        </restriction>
                    </simpleType>
                </element>
                <element name="refeição">
                    <simpleType>
                        <restriction base="string">
                            <pattern value=" cafe|almoço|janta"/>
                        </restriction>
                    </simpleType>
                </element>
                <element name="ingredientes">
                    <complexType>
                        <sequence>
                            <element name="ingrediente" type="string" minOccurs="0" maxOccurs="unbounded"/>
                        </sequence>
                    </complexType>
                </element>
                <element name="preco">
                    <simpleType>
                        <restriction base="decimal">
                            <fractionDigits value="2"/>
                        </restriction>
                    </simpleType>
                </element>
            </element name="dataCadastro" type="date">
            </sequence>
        </complexType>
    </element>

</schema>

=== hskally20/atividades-pos-2024/xml/prato.xml
<?xml version="1.0" encoding="UTF-8"?>
<prato xmlns="http://prato.org" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://prato.org prato.xsd">
    <nome>hamburg</nome>
    <refeição>janta</refeição>
    <ingredientes>
        <ingrediente> pão </ingrediente>
        <ingrediente> cebola </ingrediente>
        <ingrediente> alho </ingrediente>
        <ingrediente> carne </ingrediente>
    </ingredientes>
    <preco>12,00</preco>
    <dataCadastro>2024/08/03</dataCadastro>
</prato>
